### ISSUE TITLE
Update documentation links

### ISSUE THREAD

**Issue by eirrgang** [kassonlab/run_brer#3]
Documentation builds are no longer built (or updated) by @jmhays 

We should
- [ ] Establish hosting for documentation through a kassonlab account, and
- [ ] Update links in the repository to point to the new authoritative documentation URLs.

**Comment by jmhays** [comment]
I suggest using GitHub's hosting rather than ReadTheDocs. I found it difficult to ensure that gromacs, gmxapi, and the plugin code all compiled properly in the ReadTheDocs cloud. There is a `docs` folder in the master branch that contains built documentation. That is what I updated as the documentation changed.
